### ISSUE TITLE
Misleading CI Documentation

### ISSUE THREAD

**Issue by max-denari** [HiDeoo/vercel-env-push#27]
### Is your feature request related to a problem?

When using vercel-env-push@0.4.0 in CI, the example says to
```yaml
- name: Push environment variables from GitHub Actions
  run: pnpm vercel-env-push .env.local preview -t "$VERCEL_TOKEN"
  env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
``` 
But this will result in 
```shell
Do you want to push these environment variables? (Y/n)
```
preventing the CI from actually executing the command.

### Describe the solution you'd like

I think using `--dry-run` for testing and removing the y/n text prompt should be sufficient to fix this. It is confusing to have both without documentation as to why.

### Describe alternatives you've considered

It would also totally work if you removed the `--dry-run` flag and replaced it with `--yes | -y`

### Additional Context

Currently, the way we have it setup in our CI is to run.
```shell
yes | pnpm vercel-env-push .env.local preview -t "$VERCEL_TOKEN"
```
